version: "2.4"

services:
  mysql_db:
    image: mysql:latest
    container_name: bakery_mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  migrate:
    image: migrate/migrate
    container_name: bakery_migrations
    depends_on:
      mysql_db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql_db:3306)/${MYSQL_DATABASE}", "up" ]

  backend:
    build: .
    container_name: bakery_backend
    depends_on:
      - mysql_db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql_db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MINUTES: ${JWT_EXPIRATION_MINUTES}

volumes:
  mysql_data:
